---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# pericircumference

<!-- badges: start -->
<!-- badges: end -->

A project manager designed for workflows that generate reports, slides, or any other type of markdown output, `pericircumference` starts new projects with a standard workflow designed for analysts in Perisphere Real World Evidence.

## Installation

You can install the development version of pericircumference like so:

``` r
renv::install("perisphere-rwe/pericircumference")
```

## Purpose

`pericircumference` populates working directories with relevant files to manage your project using the `targets` package. It's intended purpose is to allow new projects to be initiated quickly and safely (e.g., without forgetting to write something important in `.gitignore`).

## File contents

Running `use_pericircumference()` in the R console will populate your current working directory with the following files and directories:

- `_targets.R`: this is the file used to coordinate targets
- `packages.R`: all `library` calls go here
- `conflicts.R`: uses `conflicted` package to manage name space
- `changelog.md`: describes changes implemented in each update (more on this below)
- `.gitignore`: manages which files and directories are ignored by git
- the `R` directory:
    + `R/create_output_directories.R`: helper function used for updates (more on this below)
    + `R/flextable`: helper functions for `flextable` objects
    + `R/summarize_each_group`: wrapper around `dplyr::summarize`, allows results to be summarized by group and include an overall summary as well.
- the `report` directory:
    + `report.Rmd`: generates the project report (can be MS word or html)
    + miscellaneous template files for styling the report
- the `slides` directory:
    + `slides.Rmd`: generates the project slides (can be MS word or html)
    + miscellaneous template files for styling the report
    
## Project management

This section focuses on Perisphere Real World Evidence and our own approach to managing projects.

**Updates**: As the project matures, we periodically send results to our team in a report, or present them using slides. We define these events as project updates. To make sure there is a clear track record of changes between each project update, we follow a standard procedure:

1. All projects start at version 0.1, with version increments based on minor and major updates.

    + Version 0.1 is considered complete when we are ready to send the first draft of results to a collaborator. It does not necessarily need to contain all of the planned outputs. 
    
    + The first version of results that contains all planned outputs for a project is called version 1.0. 
    
    + *Example*: if a project has three objectives, we may want to share results with a collaborator after completing some results in objective 1. We'd call this version 0.1. For version 0.2, we could make minor updates to the results we shared in version 0.1 based on feedback from our collaborators. For version 0.3, we could complete results for objective 2. For version 0.4, we again make minor updates to results in objectives 1 and 2 based on feedback from our collaborators. Next, we complete results for objective 3, and because this consitutes all the results in the current project, we call this version 1.0. If we make minor updates to the analysis after this, we increment the minor version (e.g., 1.1, 1.2, etc.). If we make a major update to the analysis after this (e.g., adding a fourth objective), we increment the major version (e.g., 2.0). This establishes a clear version history of results.

2. The lead analyst writes changes in the changelog **as they implement them**. 

    + To make sure your collaborators are kept informed as a project progresses, all meaningful updates to the project should be communicated to them. Proactively writing the changes in your changelog is the best way to do this. If you postpone summarizing changes, you'll spend extra time wracking your brain trying to remember what you did and you might forget some important things (ask me how I know).

1. When it's time to share the changes, the analyst runs `finalize_version()`, which will do the following:
    
    + pull the text from the changelog file and print it to your console. You can copy/paste the text into an e-mail.
    
    + reminds you to change `version_major` and/or `version_minor` in your project so that the next time you make your targets, any rendered markdown documents will be made with the new version name (this ensures you won't accidentally overwrite a previously finalized report).
    
    + reminds you to make a git commit indicating that this is the commit where a given version was finalized. This makes it easy to rewing the project to previous versions if needed. 

## Using git

It is highly recommended to use `git` in projects that are created with `use_pericircumference`, but it isn't a requirement. Personally, `git` is my preference for version control of code documents (e.g., files ending in `.R`, `.Rmd`, or `.qmd`), while `pericircumference::finalize_version()` is my preference for version control of documents created by code (e.g., files ending with `.docx`, `.html`, or `.pdf`). I prefer `pericircumference` for version control of output documents because it keeps all the previous versions accessible to you without having to navigate through commit history to fish them out, and in general using `git` to track `.docx` or other types of output files can be awkward because it is a little out of scope for `git` to do this.

## Common errors

1. Error: pandoc document conversion failed with error 1. This error occurs when you attempt to knit a word document while the document is open on your computer. To fix, simply close the document and knit again.

1. I made changes to `_targets.R` and then ran `tar_make()` but the changes were not incorporated. If this happens to you, double check to see if you saved your `_targets.R` file after making changes. The same goes for making changes to other R files that `_targets.R` uses.  
