---
title: "{{{report_title}}}"
subtitle: "Start here when making deliverables with html"
author: "{{{author}}}"
date: "Document created on `r format(Sys.time(), '%B %d, %Y')`" 
bibliography: {{{report_dir}}}/refs.bib
csl: {{{report_dir}}}/refs.csl
always_allow_html: true
format: 
  html:
    embed-resources: true
    toc: true
    toc-location: body
    css: {{{report_dir}}}/perisphere-report.css
    include-in-header: {{{report_dir}}}/toc-button.html
    toc-title: "Contents"
    toc-floating: false
    number-sections: false
    smooth-scroll: true
    theme: flatly
    code-fold: true
    code-tools: true
    highlight-style: github
    df-print: paged
    mainfont: Arial
    fontsize: 11pt
---

```{r setup-knitr, include=FALSE}

knitr::opts_chunk$set(
  echo = FALSE,    # don't show code blocks
  message = FALSE, # don't print messages to the doc
  warning = FALSE, # don't print warnings to the doc
  dpi = 300,       # higher dpi => higher render time 
  fig.width = 6,   # default figure width in inches
  fig.height = 4   # default figure height in inches
)

# Hello! This is the template html document for Perisphere reports.
# There are several code chunks used to set up the format of the
# document below. You don't have to modify those unless you want 
# to change the format of your output. 

```

```{r setup-pkgs}

# packages are usually handled by packages.R (in main directory).
# When tar_make() is run, it loads everything in packages.R.
# Assuming this document is in the list of targets (see ?tar_render),
# you won't need to include the library calls below.
# however, the template includes packages in its initial form
# so that you can knit the document without having to run tar_make().

# standards for word docs
library(officer)
library(flextable)

# specify a rounding specification 
library(periglue)

# general purpose
library(tidyverse)
library(pericircle)

# table 1
library(gtsummary)

```

```{r setup-figures}


theme_set(
  new = theme_bw() + 
    theme(panel.grid = element_blank(),
          text = element_text(size = 12))
)

```


```{r setup-targets}

# # uncomment when there are targets to load
# withr::with_dir(
#   new = here::here(),
#   code = {
#     targets::tar_load(names = c())
#   }
# )

```



```{r setup-formatters}

# make a short name for periglue::peri_value - this makes
# the inline reporting of results less complicated to read.
tv <- periglue::peri_value
tg <- periglue::peri_glue

r_version <- tg("{version$major}.{version$minor}")

```

```{r setup-tables}

# abbreviation management

abbrvs <- list(
  CI   = 'confidence interval',
  SD   = 'standard deviation',
  IQR  = 'interquartile range',
  EHR  = 'electronic health records',
  CVD  = 'cardiovascular disease'
)

abbrvs_paste <- function(strings){
  
  front <- 'Abbreviations'
  
  matter <- glue::glue_collapse(strings, sep = '; ', last = '; and ')
  
  paste(front, matter, sep = ': ')
  
}

abbrvs_write <- function(abbr){
  
  sorted <- abbr[sort(names(abbr))]
  
  strings <- map2_chr(names(sorted), sorted, paste, sep = ' = ')
  
  abbrvs_paste(strings)
  
}

```

# Overview

# Primary analysis

# Secondary analysis

# Sensitivity analysis
